version: '4.0'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/comp3123_backend
      - JWT_SECRET=password123
volumes:
  mongo_data:
